### ISSUE TITLE
Can't run Quake

### ISSUE THREAD

**Issue by Nexidian** [0xABADCAFE/php-demo-engine#14]
This engine does work, I tried to play Quake but all I got was some text

0/10

**Comment by 0xABADCAFE** [comment]
Got to raycast before you can bsp walk.

**Comment by 0xABADCAFE** [comment]
Also, you need to run it in a terminal that supports extended ANSI codes for RGB. The standard gnome terminal seems to work. besf. The default terminal in OSX is completely knackered.

**Comment by 0xABADCAFE** [comment]
Mr Jennings no less!

Your mileage may vary https://photos.app.goo.gl/bkRGaX6rWYqpW48D6
